from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import re
import secrets
import subprocess
import unicodedata
from datetime import datetime, timedelta, timezone
from http import HTTPStatus
from http.cookies import SimpleCookie
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse
from urllib.request import Request, urlopen

import psycopg
from psycopg.rows import dict_row


ROOT = Path(__file__).resolve().parent.parent
STATIC_DIR = ROOT / "static"
APP_VERSION = os.environ.get("CAMPAIGN_CODEX_VERSION", "1.0.0")
APP_REPOSITORY = os.environ.get("CAMPAIGN_CODEX_REPOSITORY", "Arinfaead/CampaignCodex")
LOG_FILE = Path(os.environ.get("CAMPAIGN_CODEX_LOG_FILE", str(ROOT / "data" / "campaigncodex.log")))
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://campaign_codex:campaign_codex@localhost:5432/campaign_codex",
)
PUBLIC_URL = os.environ.get("PUBLIC_URL", "http://localhost:8080").rstrip("/")
COOKIE_SECURE = os.environ.get("COOKIE_SECURE", "false").lower() == "true"
SESSION_DAYS = int(os.environ.get("SESSION_DAYS", "14"))

OIDC_ISSUER = os.environ.get("OIDC_ISSUER", "").rstrip("/")
OIDC_CLIENT_ID = os.environ.get("OIDC_CLIENT_ID", "")
OIDC_CLIENT_SECRET = os.environ.get("OIDC_CLIENT_SECRET", "")
OIDC_REDIRECT_URI = os.environ.get("OIDC_REDIRECT_URI", f"{PUBLIC_URL}/api/auth/oauth/callback")
OIDC_ADMIN_GROUP = os.environ.get("OIDC_ADMIN_GROUP", "CampaignCodex Admins")
OIDC_DM_GROUP = os.environ.get("OIDC_DM_GROUP", "CampaignCodex DMs")

PAGE_CATEGORIES = (
    "overview",
    "locations",
    "characters",
    "factions",
    "creatures",
    "items",
    "plots",
    "lore",
    "rules",
    "player_dossiers",
    "dm_notes",
)
DM_ONLY_CATEGORIES = ("player_dossiers", "dm_notes")
PAGE_VISIBILITIES = ("players", "dm", "restricted", "private")
MEMBERSHIP_ROLES = ("dm", "player")
GLOBAL_ROLES = ("admin", "dm", "player")
MENTION_RE = re.compile(r"\[\[([^\]\n]+)\]\]")


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def future(days: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=days)).isoformat(timespec="seconds")


def connect() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def row_to_dict(row: dict | None) -> dict | None:
    return dict(row) if row else None


def init_db() -> None:
    with connect() as db:
        db.execute(
            f"""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                display_name TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('dm', 'player')),
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS campaigns (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name TEXT NOT NULL,
                system TEXT NOT NULL DEFAULT 'D&D 5e',
                description TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS memberships (
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK(role IN ('dm', 'player')),
                PRIMARY KEY (user_id, campaign_id)
            );

            CREATE TABLE IF NOT EXISTS pages (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
                title TEXT NOT NULL,
                category TEXT NOT NULL CHECK(category IN {sql_tuple(PAGE_CATEGORIES)}),
                template_key TEXT NOT NULL DEFAULT 'generic',
                summary TEXT NOT NULL DEFAULT '',
                visibility TEXT NOT NULL CHECK(visibility IN {sql_tuple(PAGE_VISIBILITIES)}),
                body TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS session_notes (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                title TEXT NOT NULL,
                body TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
            """
        )
        migrate_schema(db)


def migrate_schema(db: psycopg.Connection) -> None:
    statements = [
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS global_role TEXT NOT NULL DEFAULT 'player'",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider TEXT NOT NULL DEFAULT 'local'",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_subject TEXT",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TEXT",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS slug TEXT",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS body_private TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS parent_id INTEGER REFERENCES pages(id) ON DELETE SET NULL",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb",
        "ALTER TABLE pages ADD COLUMN IF NOT EXISTS created_at TEXT",
        "ALTER TABLE session_notes ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'private'",
    ]
    for statement in statements:
        db.execute(statement)

    db.execute("ALTER TABLE pages DROP CONSTRAINT IF EXISTS pages_visibility_check")
    db.execute(f"ALTER TABLE pages ADD CONSTRAINT pages_visibility_check CHECK(visibility IN {sql_tuple(PAGE_VISIBILITIES)})")
    db.execute("ALTER TABLE pages DROP CONSTRAINT IF EXISTS pages_category_check")
    db.execute(f"ALTER TABLE pages ADD CONSTRAINT pages_category_check CHECK(category IN {sql_tuple(PAGE_CATEGORIES)})")
    db.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_global_role_check")
    db.execute(f"ALTER TABLE users ADD CONSTRAINT users_global_role_check CHECK(global_role IN {sql_tuple(GLOBAL_ROLES)})")

    db.execute("UPDATE users SET global_role = role WHERE global_role = 'player' AND role IN ('dm', 'player')")
    db.execute("UPDATE pages SET created_at = COALESCE(created_at, updated_at, %s) WHERE created_at IS NULL", (now(),))
    db.execute(
        """
        UPDATE pages
        SET owner_id = memberships.user_id
        FROM memberships
        WHERE pages.owner_id IS NULL
          AND pages.campaign_id = memberships.campaign_id
          AND memberships.role = 'dm'
        """
    )
    backfill_page_slugs(db)

    db.execute("CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (lower(email)) WHERE email IS NOT NULL")
    db.execute("CREATE INDEX IF NOT EXISTS pages_campaign_idx ON pages (campaign_id)")
    db.execute("CREATE UNIQUE INDEX IF NOT EXISTS pages_campaign_slug_unique ON pages (campaign_id, slug)")
    db.execute("CREATE INDEX IF NOT EXISTS pages_parent_idx ON pages (parent_id)")
    db.execute("CREATE INDEX IF NOT EXISTS session_notes_campaign_idx ON session_notes (campaign_id)")

    db.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_sessions (
            token_hash TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            expires_at TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS oauth_states (
            state_hash TEXT PRIMARY KEY,
            expires_at TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS campaign_invites (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            token_hash TEXT NOT NULL UNIQUE,
            campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
            invited_email TEXT,
            role TEXT NOT NULL CHECK(role IN ('dm', 'player')),
            created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            expires_at TEXT NOT NULL,
            accepted_at TEXT,
            created_at TEXT NOT NULL
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS page_permissions (
            page_id INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            can_read BOOLEAN NOT NULL DEFAULT true,
            can_write BOOLEAN NOT NULL DEFAULT false,
            PRIMARY KEY (page_id, user_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS category_permissions (
            campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
            category TEXT NOT NULL,
            role TEXT NOT NULL CHECK(role IN ('dm', 'player')),
            can_read BOOLEAN NOT NULL DEFAULT true,
            can_write BOOLEAN NOT NULL DEFAULT false,
            PRIMARY KEY (campaign_id, category, role)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS attachments (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
            page_id INTEGER REFERENCES pages(id) ON DELETE CASCADE,
            note_id INTEGER REFERENCES session_notes(id) ON DELETE CASCADE,
            uploaded_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            filename TEXT NOT NULL,
            mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
            content BYTEA NOT NULL,
            created_at TEXT NOT NULL,
            CHECK (page_id IS NOT NULL OR note_id IS NOT NULL)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS tags (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            slug TEXT NOT NULL,
            color TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            UNIQUE (campaign_id, slug)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS page_tags (
            page_id INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
            PRIMARY KEY (page_id, tag_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS page_relations (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
            source_page_id INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            target_page_id INTEGER REFERENCES pages(id) ON DELETE SET NULL,
            target_title TEXT NOT NULL DEFAULT '',
            relation_type TEXT NOT NULL DEFAULT 'related',
            description TEXT NOT NULL DEFAULT '',
            visibility TEXT NOT NULL CHECK(visibility IN {visibility_values}),
            created_at TEXT NOT NULL
        )
        """.format(visibility_values=sql_tuple(PAGE_VISIBILITIES))
    )
    db.execute("CREATE INDEX IF NOT EXISTS page_relations_source_idx ON page_relations (source_page_id)")
    db.execute("CREATE INDEX IF NOT EXISTS page_relations_target_idx ON page_relations (target_page_id)")
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS page_mentions (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
            source_page_id INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            target_page_id INTEGER REFERENCES pages(id) ON DELETE SET NULL,
            target_title TEXT NOT NULL,
            source_field TEXT NOT NULL,
            visibility TEXT NOT NULL CHECK(visibility IN {visibility_values}),
            created_at TEXT NOT NULL
        )
        """.format(visibility_values=sql_tuple(PAGE_VISIBILITIES))
    )
    db.execute("CREATE INDEX IF NOT EXISTS page_mentions_source_idx ON page_mentions (source_page_id)")
    db.execute("CREATE INDEX IF NOT EXISTS page_mentions_target_idx ON page_mentions (target_page_id)")
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS app_settings (
            key TEXT PRIMARY KEY,
            value JSONB NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )


def seed_database(db: psycopg.Connection, owner_user_id: int | None = None) -> int:
    timestamp = now()
    campaign_id = db.execute(
        "INSERT INTO campaigns (name, system, description, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
        (
            "Die Splitterkrone",
            "D&D 5e",
            "Eine Beispielkampagne um verlorene Erben, alte Portale und eine Krone, die niemand tragen sollte.",
            timestamp,
        ),
    ).fetchone()["id"]
    if owner_user_id:
        db.execute(
            "INSERT INTO memberships (user_id, campaign_id, role) VALUES (%s, %s, 'dm') ON CONFLICT DO NOTHING",
            (owner_user_id, campaign_id),
        )
    return campaign_id


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(STATIC_DIR), **kwargs)

    def log_message(self, format: str, *args: object) -> None:
        logging.info("%s - %s", self.address_string(), format % args)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path.startswith("/api/"):
            self.handle_api_get(parsed.path, parse_qs(parsed.query))
            return
        if parsed.path == "/":
            self.path = "/index.html"
        super().do_GET()

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        if not parsed.path.startswith("/api/"):
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        self.handle_api_post(parsed.path, self.read_json())

    def do_PUT(self) -> None:
        parsed = urlparse(self.path)
        if not parsed.path.startswith("/api/"):
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        self.handle_api_put(parsed.path, self.read_json())

    def read_json(self) -> dict:
        length = int(self.headers.get("Content-Length", "0"))
        if length == 0:
            return {}
        return json.loads(self.rfile.read(length).decode("utf-8"))

    def send_json(self, data: object, status: HTTPStatus = HTTPStatus.OK) -> None:
        encoded = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def send_json_error(self, message: str, status: HTTPStatus) -> None:
        self.send_json({"error": message}, status)

    def set_session_cookie(self, token: str) -> None:
        secure = "; Secure" if COOKIE_SECURE else ""
        self.send_header(
            "Set-Cookie",
            f"cc_session={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age={SESSION_DAYS * 86400}{secure}",
        )

    def clear_session_cookie(self) -> None:
        self.send_header("Set-Cookie", "cc_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0")

    def send_auth_json(self, token: str, data: object) -> None:
        encoded = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.set_session_cookie(token)
        self.end_headers()
        self.wfile.write(encoded)

    def redirect(self, location: str) -> None:
        self.send_response(HTTPStatus.FOUND)
        self.send_header("Location", location)
        self.end_headers()

    def current_user(self, db: psycopg.Connection) -> dict | None:
        token = self.session_token()
        if not token:
            return None
        token_hash = hash_token(token)
        session = db.execute(
            """
            SELECT auth_sessions.*, users.*
            FROM auth_sessions
            JOIN users ON users.id = auth_sessions.user_id
            WHERE auth_sessions.token_hash = %s AND auth_sessions.expires_at > %s
            """,
            (token_hash, now()),
        ).fetchone()
        return row_to_dict(session)

    def session_token(self) -> str | None:
        cookie = SimpleCookie(self.headers.get("Cookie"))
        if "cc_session" not in cookie:
            return None
        return cookie["cc_session"].value

    def handle_api_get(self, path: str, query: dict[str, list[str]]) -> None:
        with connect() as db:
            if path == "/api/auth/session":
                user = self.current_user(db)
                self.send_json({"user": public_user(user), "oauth_enabled": oauth_enabled(), "setup_required": setup_required(db)})
                return

            if path == "/api/auth/oauth/start":
                if not oauth_enabled():
                    self.send_json_error("OAuth is not configured.", HTTPStatus.BAD_REQUEST)
                    return
                state = secrets.token_urlsafe(32)
                db.execute(
                    "INSERT INTO oauth_states (state_hash, expires_at, created_at) VALUES (%s, %s, %s)",
                    (hash_token(state), future(1), now()),
                )
                authorization_params = {
                    'client_id': OIDC_CLIENT_ID,
                    'redirect_uri': OIDC_REDIRECT_URI,
                    'response_type': 'code',
                    'scope': 'openid email profile groups',
                    'state': state,
                }
                authorization_url = f"{OIDC_ISSUER}/application/o/authorize/?{urlencode(authorization_params)}"
                self.redirect(authorization_url)
                return

            if path == "/api/auth/oauth/callback":
                self.handle_oauth_callback(db, query)
                return

            user = self.current_user(db)
            if not user:
                self.send_json_error("Authentication required.", HTTPStatus.UNAUTHORIZED)
                return

            if path == "/api/bootstrap":
                campaigns = [row_to_dict(row) for row in db.execute(visible_campaigns_query(user), visible_campaigns_params(user))]
                self.send_json({"campaigns": campaigns, "user": public_user(user), "oauth_enabled": oauth_enabled()})
                return

            if path == "/api/campaign":
                campaign_id = self.required_int(query, "campaign_id")
                membership = self.membership(db, campaign_id, user["id"])
                if not can_access_campaign(user, membership):
                    self.send_json_error("User is not part of this campaign.", HTTPStatus.FORBIDDEN)
                    return
                self.send_json(self.campaign_payload(db, campaign_id, user, membership))
                return

            if path == "/api/search":
                campaign_id = self.required_int(query, "campaign_id")
                term = clean(query.get("q", [""])[0])
                membership = self.membership(db, campaign_id, user["id"])
                if not can_access_campaign(user, membership):
                    self.send_json_error("User is not part of this campaign.", HTTPStatus.FORBIDDEN)
                    return
                self.send_json({"results": self.search(db, campaign_id, user, membership, term)})
                return

            if path == "/api/invite":
                token = clean(query.get("token", [""])[0])
                invite = invite_by_token(db, token)
                if not invite:
                    self.send_json_error("Invite not found or expired.", HTTPStatus.NOT_FOUND)
                    return
                self.send_json({"invite": invite})
                return

            if path.startswith("/api/attachments/") and path.endswith("/download"):
                attachment_id = int(path.split("/")[3])
                self.download_attachment(db, attachment_id, user)
                return

            if path.startswith("/api/campaigns/") and path.endswith("/export"):
                campaign_id = int(path.split("/")[3])
                membership = self.membership(db, campaign_id, user["id"])
                if not can_manage_campaign(user, membership):
                    self.send_json_error("Only admins and DMs can export campaigns.", HTTPStatus.FORBIDDEN)
                    return
                self.send_json(export_campaign(db, campaign_id))
                return

            if path == "/api/admin/settings":
                if user["global_role"] != "admin":
                    self.send_json_error("Only admins can view system settings.", HTTPStatus.FORBIDDEN)
                    return
                self.send_json(admin_settings_payload(db))
                return

        self.send_error(HTTPStatus.NOT_FOUND)

    def handle_api_post(self, path: str, payload: dict) -> None:
        timestamp = now()
        with connect() as db:
            if path == "/api/auth/login":
                if setup_required(db):
                    self.send_json_error("Initial setup is required.", HTTPStatus.FORBIDDEN)
                    return
                email = clean(payload.get("email")).lower()
                user = db.execute("SELECT * FROM users WHERE lower(email) = lower(%s)", (email,)).fetchone()
                if not user or not verify_password(clean(payload.get("password")), user.get("password_hash")):
                    self.send_json_error("Invalid email or password.", HTTPStatus.UNAUTHORIZED)
                    return
                token = create_session(db, user["id"])
                self.send_auth_json(token, {"user": public_user(user)})
                return

            if path == "/api/setup":
                if not setup_required(db):
                    self.send_json_error("Setup has already been completed.", HTTPStatus.CONFLICT)
                    return
                display_name = clean(payload.get("display_name"))
                email = clean(payload.get("email")).lower()
                password = clean(payload.get("password"))
                if not display_name or not email or len(password) < 8:
                    self.send_json_error("Name, email and a password with at least 8 characters are required.", HTTPStatus.BAD_REQUEST)
                    return
                if db.execute("SELECT 1 FROM users WHERE lower(email) = lower(%s)", (email,)).fetchone():
                    self.send_json_error("Email already exists.", HTTPStatus.CONFLICT)
                    return
                user = db.execute(
                    """
                    INSERT INTO users (display_name, role, email, password_hash, global_role, auth_provider, created_at)
                    VALUES (%s, 'dm', %s, %s, 'admin', 'local', %s)
                    RETURNING *
                    """,
                    (display_name, email, hash_password(password), timestamp),
                ).fetchone()
                if payload.get("create_sample_campaign", True) is not False:
                    seed_database(db, user["id"])
                token = create_session(db, user["id"])
                self.send_auth_json(token, {"user": public_user(user)})
                return

            if path == "/api/auth/register":
                self.send_json_error("Self registration is disabled. Ask an admin or use an invite.", HTTPStatus.FORBIDDEN)
                return

            user = self.current_user(db)
            if not user:
                self.send_json_error("Authentication required.", HTTPStatus.UNAUTHORIZED)
                return

            if path == "/api/auth/logout":
                token = self.session_token()
                if token:
                    db.execute("DELETE FROM auth_sessions WHERE token_hash = %s", (hash_token(token),))
                encoded = b'{"ok": true}'
                self.send_response(HTTPStatus.OK)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(encoded)))
                self.clear_session_cookie()
                self.end_headers()
                self.wfile.write(encoded)
                return

            if path == "/api/users":
                if user["global_role"] != "admin":
                    self.send_json_error("Only admins can create users.", HTTPStatus.FORBIDDEN)
                    return
                new_user = create_local_user(db, payload)
                self.send_json({"user": public_user(new_user)}, HTTPStatus.CREATED)
                return

            if path == "/api/campaigns":
                if user["global_role"] not in ("admin", "dm"):
                    self.send_json_error("Only admins and DMs can create campaigns.", HTTPStatus.FORBIDDEN)
                    return
                name = clean(payload.get("name"))
                if not name:
                    self.send_json_error("Campaign name is required.", HTTPStatus.BAD_REQUEST)
                    return
                campaign = db.execute(
                    """
                    INSERT INTO campaigns (name, system, description, created_at)
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                    """,
                    (name, clean(payload.get("system")) or "D&D 5e", clean(payload.get("description")), timestamp),
                ).fetchone()
                db.execute(
                    "INSERT INTO memberships (user_id, campaign_id, role) VALUES (%s, %s, 'dm')",
                    (user["id"], campaign["id"]),
                )
                self.send_json({"id": campaign["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/pages":
                campaign_id = int(payload["campaign_id"])
                membership = self.membership(db, campaign_id, user["id"])
                if not can_access_campaign(user, membership):
                    self.send_json_error("User is not part of this campaign.", HTTPStatus.FORBIDDEN)
                    return
                category = validated(payload.get("category"), PAGE_CATEGORIES, "overview")
                if category in DM_ONLY_CATEGORIES and not can_manage_campaign(user, membership):
                    self.send_json_error("Only DMs can create pages in this category.", HTTPStatus.FORBIDDEN)
                    return
                visibility = validated(payload.get("visibility"), PAGE_VISIBILITIES, "players")
                if visibility == "dm" and not can_manage_campaign(user, membership):
                    self.send_json_error("Only DMs can create DM-only pages.", HTTPStatus.FORBIDDEN)
                    return
                body_private = payload.get("body_private", "") if can_manage_campaign(user, membership) else ""
                title = clean(payload.get("title")) or "Neue Seite"
                slug = unique_page_slug(db, campaign_id, clean(payload.get("slug")) or title)
                page = db.execute(
                    """
                    INSERT INTO pages (
                        campaign_id, owner_id, title, slug, category, template_key, summary, visibility,
                        body, body_private, status, created_at, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        campaign_id,
                        user["id"],
                        title,
                        slug,
                        category,
                        clean(payload.get("template_key")) or "generic",
                        clean(payload.get("summary")),
                        visibility,
                        payload.get("body", ""),
                        body_private,
                        clean(payload.get("status")),
                        timestamp,
                        timestamp,
                    ),
                ).fetchone()
                save_page_readers(db, page["id"], payload.get("reader_ids", []))
                save_page_tags(db, campaign_id, page["id"], payload.get("tags", []))
                save_page_relations(db, campaign_id, page["id"], payload.get("relations", []), can_manage_campaign(user, membership))
                sync_page_mentions(db, campaign_id, page["id"], payload.get("body", ""), body_private, visibility)
                resolve_unresolved_references(db, campaign_id, page["id"], title, slug)
                self.send_json({"id": page["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/notes":
                campaign_id = int(payload["campaign_id"])
                membership = self.membership(db, campaign_id, user["id"])
                if not can_access_campaign(user, membership):
                    self.send_json_error("User is not part of this campaign.", HTTPStatus.FORBIDDEN)
                    return
                note = db.execute(
                    """
                    INSERT INTO session_notes (campaign_id, user_id, title, body, updated_at)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (campaign_id, user["id"], clean(payload.get("title")) or "Neue Session-Notiz", payload.get("body", ""), timestamp),
                ).fetchone()
                self.send_json({"id": note["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/invites":
                campaign_id = int(payload["campaign_id"])
                membership = self.membership(db, campaign_id, user["id"])
                if not can_manage_campaign(user, membership):
                    self.send_json_error("Only DMs can create invites.", HTTPStatus.FORBIDDEN)
                    return
                token = secrets.token_urlsafe(32)
                db.execute(
                    """
                    INSERT INTO campaign_invites (token_hash, campaign_id, invited_email, role, created_by, expires_at, created_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        hash_token(token),
                        campaign_id,
                        clean(payload.get("email")).lower() or None,
                        validated(payload.get("role"), MEMBERSHIP_ROLES, "player"),
                        user["id"],
                        future(int(payload.get("expires_days", 14))),
                        timestamp,
                    ),
                )
                self.send_json({"invite_url": f"{PUBLIC_URL}/?invite={token}"}, HTTPStatus.CREATED)
                return

            if path == "/api/invites/accept":
                invite = invite_by_token(db, clean(payload.get("token")))
                if not invite:
                    self.send_json_error("Invite not found or expired.", HTTPStatus.NOT_FOUND)
                    return
                if invite["invited_email"] and (user.get("email") or "").lower() != invite["invited_email"]:
                    self.send_json_error("This invite was created for a different email address.", HTTPStatus.FORBIDDEN)
                    return
                db.execute(
                    """
                    INSERT INTO memberships (user_id, campaign_id, role)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(user_id, campaign_id) DO UPDATE SET role = excluded.role
                    """,
                    (user["id"], invite["campaign_id"], invite["role"]),
                )
                db.execute("UPDATE campaign_invites SET accepted_at = %s WHERE id = %s", (timestamp, invite["id"]))
                self.send_json({"ok": True})
                return

            if path == "/api/members":
                campaign_id = int(payload["campaign_id"])
                membership = self.membership(db, campaign_id, user["id"])
                if not can_manage_campaign(user, membership):
                    self.send_json_error("Only DMs can add campaign members.", HTTPStatus.FORBIDDEN)
                    return
                target = db.execute("SELECT * FROM users WHERE lower(email) = lower(%s)", (clean(payload.get("email")),)).fetchone()
                if not target:
                    self.send_json_error("User must already have a CampaignCodex account. Create an invite or local account first.", HTTPStatus.NOT_FOUND)
                    return
                db.execute(
                    """
                    INSERT INTO memberships (user_id, campaign_id, role)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(user_id, campaign_id) DO UPDATE SET role = excluded.role
                    """,
                    (target["id"], campaign_id, validated(payload.get("role"), MEMBERSHIP_ROLES, "player")),
                )
                self.send_json({"id": target["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/attachments":
                self.create_attachment(db, user, payload)
                return

            if path == "/api/campaigns/import":
                if user["global_role"] not in ("admin", "dm"):
                    self.send_json_error("Only admins and DMs can import campaigns.", HTTPStatus.FORBIDDEN)
                    return
                campaign_id = import_campaign(db, user, payload)
                self.send_json({"id": campaign_id}, HTTPStatus.CREATED)
                return

            if path == "/api/admin/settings":
                if user["global_role"] != "admin":
                    self.send_json_error("Only admins can update system settings.", HTTPStatus.FORBIDDEN)
                    return
                settings = save_admin_settings(db, payload.get("settings", payload))
                self.send_json({"settings": settings})
                return

            if path == "/api/admin/update-check":
                if user["global_role"] != "admin":
                    self.send_json_error("Only admins can check for updates.", HTTPStatus.FORBIDDEN)
                    return
                include_prereleases = bool(payload.get("include_prereleases", load_admin_settings(db)["general"]["include_beta_releases"]))
                self.send_json(check_for_update(include_prereleases))
                return

            if path == "/api/admin/update":
                if user["global_role"] != "admin":
                    self.send_json_error("Only admins can trigger updates.", HTTPStatus.FORBIDDEN)
                    return
                self.send_json(run_update_command(db))
                return

        self.send_error(HTTPStatus.NOT_FOUND)

    def handle_api_put(self, path: str, payload: dict) -> None:
        timestamp = now()
        with connect() as db:
            user = self.current_user(db)
            if not user:
                self.send_json_error("Authentication required.", HTTPStatus.UNAUTHORIZED)
                return

            if path.startswith("/api/pages/"):
                page_id = int(path.rsplit("/", 1)[1])
                page = db.execute("SELECT * FROM pages WHERE id = %s", (page_id,)).fetchone()
                if not page:
                    self.send_error(HTTPStatus.NOT_FOUND)
                    return
                membership = self.membership(db, page["campaign_id"], user["id"])
                if not can_edit_page(user, membership, page):
                    self.send_json_error("You cannot edit this page.", HTTPStatus.FORBIDDEN)
                    return
                category = validated(payload.get("category"), PAGE_CATEGORIES, page["category"])
                visibility = validated(payload.get("visibility"), PAGE_VISIBILITIES, page["visibility"])
                if category in DM_ONLY_CATEGORIES and not can_manage_campaign(user, membership):
                    self.send_json_error("Only DMs can use this category.", HTTPStatus.FORBIDDEN)
                    return
                if visibility == "dm" and not can_manage_campaign(user, membership):
                    self.send_json_error("Only DMs can create DM-only pages.", HTTPStatus.FORBIDDEN)
                    return
                title = clean(payload.get("title")) or "Unbenannte Seite"
                slug = unique_page_slug(db, page["campaign_id"], clean(payload.get("slug")) or title, page_id)
                body_private = payload.get("body_private", page.get("body_private", "")) if can_manage_campaign(user, membership) else page.get("body_private", "")
                db.execute(
                    """
                    UPDATE pages
                    SET title = %s, slug = %s, category = %s, template_key = %s, summary = %s,
                        visibility = %s, body = %s, body_private = %s, status = %s, updated_at = %s
                    WHERE id = %s
                    """,
                    (
                        title,
                        slug,
                        category,
                        clean(payload.get("template_key")) or page["template_key"],
                        clean(payload.get("summary")),
                        visibility,
                        payload.get("body", ""),
                        body_private,
                        clean(payload.get("status")),
                        timestamp,
                        page_id,
                    ),
                )
                save_page_readers(db, page_id, payload.get("reader_ids", []))
                save_page_tags(db, page["campaign_id"], page_id, payload.get("tags", []))
                save_page_relations(db, page["campaign_id"], page_id, payload.get("relations", []), can_manage_campaign(user, membership))
                sync_page_mentions(db, page["campaign_id"], page_id, payload.get("body", ""), body_private, visibility)
                resolve_unresolved_references(db, page["campaign_id"], page_id, title, slug)
                self.send_json({"ok": True})
                return

            if path.startswith("/api/notes/"):
                note_id = int(path.rsplit("/", 1)[1])
                note = db.execute("SELECT * FROM session_notes WHERE id = %s", (note_id,)).fetchone()
                if not note:
                    self.send_error(HTTPStatus.NOT_FOUND)
                    return
                membership = self.membership(db, note["campaign_id"], user["id"])
                if not membership or (not can_manage_campaign(user, membership) and note["user_id"] != user["id"]):
                    self.send_json_error("You can only edit your own notes.", HTTPStatus.FORBIDDEN)
                    return
                db.execute(
                    "UPDATE session_notes SET title = %s, body = %s, updated_at = %s WHERE id = %s",
                    (clean(payload.get("title")) or "Unbenannte Notiz", payload.get("body", ""), timestamp, note_id),
                )
                self.send_json({"ok": True})
                return

        self.send_error(HTTPStatus.NOT_FOUND)

    def campaign_payload(self, db: psycopg.Connection, campaign_id: int, user: dict, membership: dict | None) -> dict:
        campaign = row_to_dict(db.execute("SELECT * FROM campaigns WHERE id = %s", (campaign_id,)).fetchone())
        all_pages = [row_to_dict(row) for row in db.execute("SELECT * FROM pages WHERE campaign_id = %s ORDER BY category, title", (campaign_id,))]
        pages = [page for page in all_pages if can_read_page(db, user, membership, page)]
        pages = enrich_pages(db, pages, user, membership)
        notes = [
            row_to_dict(row)
            for row in db.execute(
                """
                SELECT session_notes.*, users.display_name AS author
                FROM session_notes
                JOIN users ON users.id = session_notes.user_id
                WHERE campaign_id = %s AND (%s = true OR user_id = %s)
                ORDER BY updated_at DESC
                """,
                (campaign_id, can_manage_campaign(user, membership), user["id"]),
            )
        ]
        members = [
            row_to_dict(row)
            for row in db.execute(
                """
                SELECT users.id, users.display_name, users.email, memberships.role
                FROM memberships
                JOIN users ON users.id = memberships.user_id
                WHERE campaign_id = %s
                ORDER BY memberships.role, users.display_name
                """,
                (campaign_id,),
            )
        ]
        attachments = visible_attachments(db, user, membership, pages, notes)
        page_readers = readers_by_page(db, [page["id"] for page in pages])
        invites = []
        users = []
        category_permissions = []
        if can_manage_campaign(user, membership):
            invites = [
                row_to_dict(row)
                for row in db.execute(
                    """
                    SELECT campaign_invites.id, campaign_invites.invited_email, campaign_invites.role,
                           campaign_invites.expires_at, campaign_invites.accepted_at, users.display_name AS created_by_name
                    FROM campaign_invites
                    JOIN users ON users.id = campaign_invites.created_by
                    WHERE campaign_id = %s
                    ORDER BY campaign_invites.created_at DESC
                    """,
                    (campaign_id,),
                )
            ]
            if user["global_role"] == "admin":
                users = [public_user(row) for row in db.execute("SELECT * FROM users ORDER BY display_name")]
            else:
                users = [
                    public_user(row)
                    for row in db.execute(
                        """
                        SELECT users.*
                        FROM users
                        JOIN memberships ON memberships.user_id = users.id
                        WHERE memberships.campaign_id = %s
                        ORDER BY users.display_name
                        """,
                        (campaign_id,),
                    )
                ]
            category_permissions = [
                row_to_dict(row)
                for row in db.execute(
                    "SELECT * FROM category_permissions WHERE campaign_id = %s ORDER BY category, role",
                    (campaign_id,),
                )
            ]
        return {
            "campaign": campaign,
            "membership": row_to_dict(membership),
            "pages": pages,
            "notes": notes,
            "members": members,
            "attachments": attachments,
            "page_readers": page_readers,
            "invites": invites,
            "users": users,
            "category_permissions": category_permissions,
            "tags": tags_for_campaign(db, campaign_id, [page["id"] for page in pages]),
            "current_user": public_user(user),
        }

    def membership(self, db: psycopg.Connection, campaign_id: int, user_id: int) -> dict | None:
        return db.execute(
            "SELECT * FROM memberships WHERE campaign_id = %s AND user_id = %s",
            (campaign_id, user_id),
        ).fetchone()

    def search(self, db: psycopg.Connection, campaign_id: int, user: dict, membership: dict | None, term: str) -> list[dict]:
        if not term:
            return []
        like = f"%{term}%"
        can_see_private = can_manage_campaign(user, membership)
        private_clause = "OR body_private ILIKE %s" if can_see_private else ""
        page_params: tuple = (campaign_id, like, like, like, like, like) if can_see_private else (campaign_id, like, like, like, like)
        rows = db.execute(
            f"""
            SELECT 'page' AS type, id, title, summary, body, body_private, category, updated_at, NULL::TEXT AS author
            FROM pages
            WHERE campaign_id = %s
              AND (
                title ILIKE %s
                OR summary ILIKE %s
                OR body ILIKE %s
                {private_clause}
                OR EXISTS (
                    SELECT 1
                    FROM page_tags
                    JOIN tags ON tags.id = page_tags.tag_id
                    WHERE page_tags.page_id = pages.id AND tags.name ILIKE %s
                )
              )
            UNION ALL
            SELECT 'note' AS type, session_notes.id, session_notes.title, '' AS summary, session_notes.body, '' AS body_private,
                   'notes' AS category, session_notes.updated_at, users.display_name AS author
            FROM session_notes
            JOIN users ON users.id = session_notes.user_id
            WHERE session_notes.campaign_id = %s AND (session_notes.title ILIKE %s OR session_notes.body ILIKE %s)
            ORDER BY updated_at DESC
            LIMIT 50
            """,
            (*page_params, campaign_id, like, like),
        ).fetchall()
        results = []
        for row in rows:
            item = row_to_dict(row)
            if item["type"] == "page":
                page = db.execute("SELECT * FROM pages WHERE id = %s", (item["id"],)).fetchone()
                if not can_read_page(db, user, membership, page):
                    continue
            elif not can_manage_campaign(user, membership):
                note = db.execute("SELECT * FROM session_notes WHERE id = %s", (item["id"],)).fetchone()
                if note["user_id"] != user["id"]:
                    continue
            item["excerpt"] = make_page_excerpt(item, term, can_see_private)
            results.append(item)
        return results

    def create_attachment(self, db: psycopg.Connection, user: dict, payload: dict) -> None:
        page_id = payload.get("page_id")
        note_id = payload.get("note_id")
        campaign_id = int(payload["campaign_id"])
        membership = self.membership(db, campaign_id, user["id"])
        if not can_access_campaign(user, membership):
            self.send_json_error("User is not part of this campaign.", HTTPStatus.FORBIDDEN)
            return
        if page_id:
            page = db.execute("SELECT * FROM pages WHERE id = %s", (int(page_id),)).fetchone()
            if not page or not can_edit_page(user, membership, page):
                self.send_json_error("You cannot attach files to this page.", HTTPStatus.FORBIDDEN)
                return
        if note_id:
            note = db.execute("SELECT * FROM session_notes WHERE id = %s", (int(note_id),)).fetchone()
            if not note or (not can_manage_campaign(user, membership) and note["user_id"] != user["id"]):
                self.send_json_error("You cannot attach files to this note.", HTTPStatus.FORBIDDEN)
                return
        content = base64.b64decode(payload.get("data_base64", ""))
        attachment = db.execute(
            """
            INSERT INTO attachments (campaign_id, page_id, note_id, uploaded_by, filename, mime_type, content, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                campaign_id,
                int(page_id) if page_id else None,
                int(note_id) if note_id else None,
                user["id"],
                clean(payload.get("filename")) or "attachment",
                clean(payload.get("mime_type")) or "application/octet-stream",
                content,
                now(),
            ),
        ).fetchone()
        self.send_json({"id": attachment["id"]}, HTTPStatus.CREATED)

    def download_attachment(self, db: psycopg.Connection, attachment_id: int, user: dict) -> None:
        attachment = db.execute("SELECT * FROM attachments WHERE id = %s", (attachment_id,)).fetchone()
        if not attachment:
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        membership = self.membership(db, attachment["campaign_id"], user["id"])
        if not can_access_campaign(user, membership):
            self.send_error(HTTPStatus.FORBIDDEN)
            return
        if attachment["page_id"]:
            page = db.execute("SELECT * FROM pages WHERE id = %s", (attachment["page_id"],)).fetchone()
            if not can_read_page(db, user, membership, page):
                self.send_error(HTTPStatus.FORBIDDEN)
                return
        if attachment["note_id"] and not can_manage_campaign(user, membership):
            note = db.execute("SELECT * FROM session_notes WHERE id = %s", (attachment["note_id"],)).fetchone()
            if note["user_id"] != user["id"]:
                self.send_error(HTTPStatus.FORBIDDEN)
                return
        content = bytes(attachment["content"])
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", attachment["mime_type"])
        self.send_header("Content-Length", str(len(content)))
        self.send_header("Content-Disposition", f'inline; filename="{attachment["filename"]}"')
        self.end_headers()
        self.wfile.write(content)

    def handle_oauth_callback(self, db: psycopg.Connection, query: dict[str, list[str]]) -> None:
        code = clean(query.get("code", [""])[0])
        state = clean(query.get("state", [""])[0])
        stored_state = db.execute(
            "SELECT * FROM oauth_states WHERE state_hash = %s AND expires_at > %s",
            (hash_token(state), now()),
        ).fetchone()
        if not code or not stored_state:
            self.redirect("/?auth_error=oauth_state")
            return
        db.execute("DELETE FROM oauth_states WHERE state_hash = %s", (hash_token(state),))
        token_data = post_form(
            f"{OIDC_ISSUER}/application/o/token/",
            {
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": OIDC_REDIRECT_URI,
                "client_id": OIDC_CLIENT_ID,
                "client_secret": OIDC_CLIENT_SECRET,
            },
        )
        userinfo = get_json(
            f"{OIDC_ISSUER}/application/o/userinfo/",
            token_data["access_token"],
        )
        user = upsert_oauth_user(db, userinfo)
        token = create_session(db, user["id"])
        encoded = b""
        self.send_response(HTTPStatus.FOUND)
        self.send_header("Location", "/")
        self.set_session_cookie(token)
        self.send_header("Content-Length", "0")
        self.end_headers()
        self.wfile.write(encoded)

    def required_int(self, query: dict[str, list[str]], key: str) -> int:
        return int(query.get(key, ["0"])[0])


def can_access_campaign(user: dict, membership: dict | None) -> bool:
    return user["global_role"] == "admin" or bool(membership)


def can_manage_campaign(user: dict, membership: dict | None) -> bool:
    return user["global_role"] == "admin" or bool(membership and membership["role"] == "dm")


def can_edit_page(user: dict, membership: dict | None, page: dict) -> bool:
    if can_manage_campaign(user, membership):
        return True
    if not membership:
        return False
    return page.get("owner_id") == user["id"]


def can_read_page(db: psycopg.Connection, user: dict, membership: dict | None, page: dict) -> bool:
    if not can_access_campaign(user, membership):
        return False
    if can_manage_campaign(user, membership):
        return True
    if page["owner_id"] == user["id"]:
        return True
    if page["category"] in DM_ONLY_CATEGORIES or page["visibility"] == "dm":
        return False
    if membership and not can_read_category(db, page["campaign_id"], page["category"], membership["role"]):
        return False
    if page["visibility"] == "private":
        return False
    if page["visibility"] == "restricted":
        acl = db.execute(
            "SELECT can_read FROM page_permissions WHERE page_id = %s AND user_id = %s",
            (page["id"], user["id"]),
        ).fetchone()
        return bool(acl and acl["can_read"])
    return True


def can_read_category(db: psycopg.Connection, campaign_id: int, category: str, role: str) -> bool:
    permission = db.execute(
        """
        SELECT can_read
        FROM category_permissions
        WHERE campaign_id = %s AND category = %s AND role = %s
        """,
        (campaign_id, category, role),
    ).fetchone()
    return True if permission is None else bool(permission["can_read"])


def visible_attachments(db: psycopg.Connection, user: dict, membership: dict | None, pages: list[dict], notes: list[dict]) -> list[dict]:
    page_ids = [page["id"] for page in pages] or [0]
    note_ids = [note["id"] for note in notes] or [0]
    rows = db.execute(
        """
        SELECT id, campaign_id, page_id, note_id, filename, mime_type, created_at
        FROM attachments
        WHERE page_id = ANY(%s) OR note_id = ANY(%s)
        ORDER BY created_at DESC
        """,
        (page_ids, note_ids),
    ).fetchall()
    return [row_to_dict(row) for row in rows]


def readers_by_page(db: psycopg.Connection, page_ids: list[int]) -> dict[str, list[int]]:
    if not page_ids:
        return {}
    rows = db.execute(
        "SELECT page_id, user_id FROM page_permissions WHERE page_id = ANY(%s) AND can_read = true",
        (page_ids,),
    ).fetchall()
    result: dict[str, list[int]] = {}
    for row in rows:
        result.setdefault(str(row["page_id"]), []).append(row["user_id"])
    return result


def save_page_readers(db: psycopg.Connection, page_id: int, reader_ids: list) -> None:
    db.execute("DELETE FROM page_permissions WHERE page_id = %s", (page_id,))
    clean_ids = sorted({int(user_id) for user_id in reader_ids if str(user_id).isdigit()})
    with db.cursor() as cursor:
        cursor.executemany(
            "INSERT INTO page_permissions (page_id, user_id, can_read) VALUES (%s, %s, true)",
            [(page_id, user_id) for user_id in clean_ids],
        )


def backfill_page_slugs(db: psycopg.Connection) -> None:
    rows = [row_to_dict(row) for row in db.execute("SELECT id, campaign_id, title, slug FROM pages ORDER BY campaign_id, id")]
    used: dict[int, set[str]] = {}
    for row in rows:
        campaign_id = row["campaign_id"]
        used.setdefault(campaign_id, set())
        base = slugify(row.get("slug") or row["title"]) or f"seite-{row['id']}"
        slug = base
        counter = 2
        while slug in used[campaign_id]:
            slug = f"{base}-{counter}"
            counter += 1
        used[campaign_id].add(slug)
        if row.get("slug") != slug:
            db.execute("UPDATE pages SET slug = %s WHERE id = %s", (slug, row["id"]))


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", clean(value)).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", normalized.lower()).strip("-")
    return slug or "seite"


def unique_page_slug(db: psycopg.Connection, campaign_id: int, value: str, page_id: int | None = None) -> str:
    base = slugify(value)
    slug = base
    counter = 2
    while True:
        params: tuple = (campaign_id, slug) if page_id is None else (campaign_id, slug, page_id)
        query = "SELECT 1 FROM pages WHERE campaign_id = %s AND slug = %s"
        if page_id is not None:
            query += " AND id <> %s"
        if not db.execute(query, params).fetchone():
            return slug
        slug = f"{base}-{counter}"
        counter += 1


def normalize_tag_names(tags: object) -> list[str]:
    if isinstance(tags, str):
        candidates = tags.split(",")
    elif isinstance(tags, list):
        candidates = tags
    else:
        candidates = []
    result = []
    seen = set()
    for value in candidates:
        name = clean(value)
        key = name.lower()
        if name and key not in seen:
            seen.add(key)
            result.append(name[:60])
    return result


def save_page_tags(db: psycopg.Connection, campaign_id: int, page_id: int, tags: object) -> None:
    db.execute("DELETE FROM page_tags WHERE page_id = %s", (page_id,))
    for name in normalize_tag_names(tags):
        slug = slugify(name)
        tag = db.execute(
            """
            INSERT INTO tags (campaign_id, name, slug, created_at)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (campaign_id, slug) DO UPDATE SET name = excluded.name
            RETURNING id
            """,
            (campaign_id, name, slug, now()),
        ).fetchone()
        db.execute(
            "INSERT INTO page_tags (page_id, tag_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
            (page_id, tag["id"]),
        )


def save_page_relations(db: psycopg.Connection, campaign_id: int, page_id: int, relations: object, can_store_private: bool) -> None:
    db.execute("DELETE FROM page_relations WHERE source_page_id = %s", (page_id,))
    if not isinstance(relations, list):
        return
    for relation in relations:
        if not isinstance(relation, dict):
            continue
        target_title = clean(relation.get("target_title"))
        target_id = relation.get("target_page_id")
        target = None
        if str(target_id or "").isdigit():
            target = db.execute(
                "SELECT id, title FROM pages WHERE campaign_id = %s AND id = %s",
                (campaign_id, int(target_id)),
            ).fetchone()
        if not target and target_title:
            target = find_page_by_title_or_slug(db, campaign_id, target_title)
        if target:
            target_id = target["id"]
            target_title = target["title"]
        if not target_title:
            continue
        visibility = validated(relation.get("visibility"), PAGE_VISIBILITIES, "players")
        if visibility in ("dm", "private") and not can_store_private:
            visibility = "players"
        db.execute(
            """
            INSERT INTO page_relations (
                campaign_id, source_page_id, target_page_id, target_title,
                relation_type, description, visibility, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                campaign_id,
                page_id,
                int(target_id) if str(target_id or "").isdigit() else None,
                target_title[:160],
                clean(relation.get("relation_type")) or "related",
                clean(relation.get("description")),
                visibility,
                now(),
            ),
        )


def find_page_by_title_or_slug(db: psycopg.Connection, campaign_id: int, value: str) -> dict | None:
    lookup = clean(value)
    return db.execute(
        """
        SELECT id, title, slug
        FROM pages
        WHERE campaign_id = %s AND (lower(title) = lower(%s) OR slug = %s)
        ORDER BY id
        LIMIT 1
        """,
        (campaign_id, lookup, slugify(lookup)),
    ).fetchone()


def sync_page_mentions(db: psycopg.Connection, campaign_id: int, page_id: int, public_body: str, private_body: str, page_visibility: str) -> None:
    db.execute("DELETE FROM page_mentions WHERE source_page_id = %s", (page_id,))
    mention_sources = [
        ("body", public_body or "", page_visibility),
        ("body_private", private_body or "", "dm"),
    ]
    seen = set()
    for source_field, markdown, visibility in mention_sources:
        for raw in MENTION_RE.findall(markdown):
            target_title = clean(raw.split("|", 1)[0])
            if not target_title:
                continue
            key = (source_field, target_title.lower())
            if key in seen:
                continue
            seen.add(key)
            target = find_page_by_title_or_slug(db, campaign_id, target_title)
            db.execute(
                """
                INSERT INTO page_mentions (
                    campaign_id, source_page_id, target_page_id, target_title,
                    source_field, visibility, created_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    campaign_id,
                    page_id,
                    target["id"] if target else None,
                    target["title"] if target else target_title[:160],
                    source_field,
                    visibility,
                    now(),
                ),
            )


def resolve_unresolved_references(db: psycopg.Connection, campaign_id: int, page_id: int, title: str, slug: str) -> None:
    db.execute(
        """
        UPDATE page_mentions
        SET target_page_id = %s, target_title = %s
        WHERE campaign_id = %s
          AND target_page_id IS NULL
          AND (lower(target_title) = lower(%s) OR lower(target_title) = lower(%s))
        """,
        (page_id, title, campaign_id, title, slug),
    )
    db.execute(
        """
        UPDATE page_relations
        SET target_page_id = %s, target_title = %s
        WHERE campaign_id = %s
          AND target_page_id IS NULL
          AND (lower(target_title) = lower(%s) OR lower(target_title) = lower(%s))
        """,
        (page_id, title, campaign_id, title, slug),
    )


def tags_for_campaign(db: psycopg.Connection, campaign_id: int, visible_page_ids: list[int]) -> list[dict]:
    if not visible_page_ids:
        return []
    return [
        row_to_dict(row)
        for row in db.execute(
            """
            SELECT DISTINCT tags.id, tags.name, tags.slug, tags.color
            FROM tags
            JOIN page_tags ON page_tags.tag_id = tags.id
            WHERE tags.campaign_id = %s AND page_tags.page_id = ANY(%s)
            ORDER BY tags.name
            """,
            (campaign_id, visible_page_ids),
        )
    ]


def enrich_pages(db: psycopg.Connection, pages: list[dict], user: dict, membership: dict | None) -> list[dict]:
    if not pages:
        return []
    page_ids = [page["id"] for page in pages]
    visible_ids = set(page_ids)
    manageable = can_manage_campaign(user, membership)
    tags_by_page = page_tags_map(db, page_ids)
    relations_by_source = page_relations_map(db, page_ids, visible_ids, manageable)
    backlinks_by_target = page_backlinks_map(db, page_ids, visible_ids, manageable)
    mentions_by_source = page_mentions_map(db, page_ids, manageable)
    result = []
    for page in pages:
        page = dict(page)
        if not manageable:
            page["body_private"] = ""
        page["tags"] = tags_by_page.get(page["id"], [])
        page["relations"] = relations_by_source.get(page["id"], [])
        page["backlinks"] = backlinks_by_target.get(page["id"], [])
        page["mentions"] = mentions_by_source.get(page["id"], [])
        result.append(page)
    return result


def page_tags_map(db: psycopg.Connection, page_ids: list[int]) -> dict[int, list[str]]:
    rows = db.execute(
        """
        SELECT page_tags.page_id, tags.name
        FROM page_tags
        JOIN tags ON tags.id = page_tags.tag_id
        WHERE page_tags.page_id = ANY(%s)
        ORDER BY tags.name
        """,
        (page_ids,),
    ).fetchall()
    result: dict[int, list[str]] = {}
    for row in rows:
        result.setdefault(row["page_id"], []).append(row["name"])
    return result


def page_relations_map(db: psycopg.Connection, page_ids: list[int], visible_ids: set[int], manageable: bool) -> dict[int, list[dict]]:
    rows = db.execute(
        """
        SELECT page_relations.*, pages.title AS resolved_target_title, pages.slug AS target_slug
        FROM page_relations
        LEFT JOIN pages ON pages.id = page_relations.target_page_id
        WHERE source_page_id = ANY(%s)
        ORDER BY relation_type, target_title
        """,
        (page_ids,),
    ).fetchall()
    result: dict[int, list[dict]] = {}
    for row in rows:
        relation = row_to_dict(row)
        if not manageable and relation["visibility"] in ("dm", "private"):
            continue
        if relation["target_page_id"] and relation["target_page_id"] not in visible_ids:
            continue
        relation["target_title"] = relation["resolved_target_title"] or relation["target_title"]
        result.setdefault(relation["source_page_id"], []).append(relation)
    return result


def page_backlinks_map(db: psycopg.Connection, page_ids: list[int], visible_ids: set[int], manageable: bool) -> dict[int, list[dict]]:
    rows = db.execute(
        """
        SELECT page_mentions.*, pages.title AS source_title, pages.slug AS source_slug
        FROM page_mentions
        JOIN pages ON pages.id = page_mentions.source_page_id
        WHERE page_mentions.target_page_id = ANY(%s)
        ORDER BY pages.title
        """,
        (page_ids,),
    ).fetchall()
    result: dict[int, list[dict]] = {}
    for row in rows:
        backlink = row_to_dict(row)
        if backlink["source_page_id"] not in visible_ids:
            continue
        if not manageable and backlink["visibility"] in ("dm", "private"):
            continue
        result.setdefault(backlink["target_page_id"], []).append(backlink)
    return result


def page_mentions_map(db: psycopg.Connection, page_ids: list[int], manageable: bool) -> dict[int, list[dict]]:
    rows = db.execute(
        """
        SELECT page_mentions.*, pages.slug AS target_slug
        FROM page_mentions
        LEFT JOIN pages ON pages.id = page_mentions.target_page_id
        WHERE source_page_id = ANY(%s)
        ORDER BY target_title
        """,
        (page_ids,),
    ).fetchall()
    result: dict[int, list[dict]] = {}
    for row in rows:
        mention = row_to_dict(row)
        if not manageable and mention["visibility"] in ("dm", "private"):
            continue
        result.setdefault(mention["source_page_id"], []).append(mention)
    return result


def create_session(db: psycopg.Connection, user_id: int) -> str:
    token = secrets.token_urlsafe(40)
    db.execute(
        "INSERT INTO auth_sessions (token_hash, user_id, expires_at, created_at) VALUES (%s, %s, %s, %s)",
        (hash_token(token), user_id, future(SESSION_DAYS), now()),
    )
    db.execute("UPDATE users SET last_login_at = %s WHERE id = %s", (now(), user_id))
    return token


def create_local_user(db: psycopg.Connection, payload: dict) -> dict:
    email = clean(payload.get("email")).lower()
    password = clean(payload.get("password"))
    display_name = clean(payload.get("display_name"))
    global_role = validated(payload.get("global_role"), GLOBAL_ROLES, "player")
    role = "dm" if global_role in ("admin", "dm") else "player"
    return db.execute(
        """
        INSERT INTO users (display_name, role, email, password_hash, global_role, auth_provider, created_at)
        VALUES (%s, %s, %s, %s, %s, 'local', %s)
        RETURNING *
        """,
        (display_name, role, email, hash_password(password), global_role, now()),
    ).fetchone()


def setup_required(db: psycopg.Connection) -> bool:
    return db.execute("SELECT COUNT(*) AS count FROM users WHERE global_role = 'admin'").fetchone()["count"] == 0


def invite_by_token(db: psycopg.Connection, token: str) -> dict | None:
    if not token:
        return None
    invite = db.execute(
        """
        SELECT campaign_invites.*, campaigns.name AS campaign_name
        FROM campaign_invites
        JOIN campaigns ON campaigns.id = campaign_invites.campaign_id
        WHERE token_hash = %s AND expires_at > %s AND accepted_at IS NULL
        """,
        (hash_token(token), now()),
    ).fetchone()
    return row_to_dict(invite)


def export_campaign(db: psycopg.Connection, campaign_id: int) -> dict:
    campaign = row_to_dict(db.execute("SELECT * FROM campaigns WHERE id = %s", (campaign_id,)).fetchone())
    pages = [row_to_dict(row) for row in db.execute("SELECT * FROM pages WHERE campaign_id = %s ORDER BY id", (campaign_id,))]
    notes = [row_to_dict(row) for row in db.execute("SELECT * FROM session_notes WHERE campaign_id = %s ORDER BY id", (campaign_id,))]
    memberships = [row_to_dict(row) for row in db.execute("SELECT * FROM memberships WHERE campaign_id = %s", (campaign_id,))]
    tags = [row_to_dict(row) for row in db.execute("SELECT * FROM tags WHERE campaign_id = %s ORDER BY id", (campaign_id,))]
    page_tags = [
        row_to_dict(row)
        for row in db.execute(
            """
            SELECT page_tags.*
            FROM page_tags
            JOIN pages ON pages.id = page_tags.page_id
            WHERE pages.campaign_id = %s
            ORDER BY page_tags.page_id, page_tags.tag_id
            """,
            (campaign_id,),
        )
    ]
    page_relations = [row_to_dict(row) for row in db.execute("SELECT * FROM page_relations WHERE campaign_id = %s ORDER BY id", (campaign_id,))]
    attachments = []
    for row in db.execute("SELECT * FROM attachments WHERE campaign_id = %s ORDER BY id", (campaign_id,)):
        item = row_to_dict(row)
        item["content_base64"] = base64.b64encode(bytes(item.pop("content"))).decode("ascii")
        attachments.append(item)
    return {
        "format": "campaigncodex.v2",
        "exported_at": now(),
        "campaign": campaign,
        "pages": pages,
        "tags": tags,
        "page_tags": page_tags,
        "page_relations": page_relations,
        "notes": notes,
        "memberships": memberships,
        "attachments": attachments,
    }


def import_campaign(db: psycopg.Connection, user: dict, payload: dict) -> int:
    data = payload.get("data", payload)
    campaign = data["campaign"]
    timestamp = now()
    new_campaign_id = db.execute(
        "INSERT INTO campaigns (name, system, description, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
        (
            f"{campaign['name']} Import",
            campaign.get("system", "D&D 5e"),
            campaign.get("description", ""),
            timestamp,
        ),
    ).fetchone()["id"]
    db.execute(
        "INSERT INTO memberships (user_id, campaign_id, role) VALUES (%s, %s, 'dm')",
        (user["id"], new_campaign_id),
    )
    page_id_map = {}
    note_id_map = {}
    tag_id_map = {}
    for page in data.get("pages", []):
        title = page.get("title", "Importierte Seite")
        new_page = db.execute(
            """
            INSERT INTO pages (
                campaign_id, owner_id, title, slug, category, template_key, summary, visibility,
                body, body_private, status, metadata, created_at, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s, %s)
            RETURNING id
            """,
            (
                new_campaign_id,
                user["id"],
                title,
                unique_page_slug(db, new_campaign_id, page.get("slug") or title),
                page["category"],
                page.get("template_key", "generic"),
                page.get("summary", ""),
                page.get("visibility", "players"),
                page.get("body", ""),
                page.get("body_private", ""),
                page.get("status", ""),
                json.dumps(page.get("metadata") or {}),
                timestamp,
                timestamp,
            ),
        ).fetchone()
        page_id_map[page["id"]] = new_page["id"]
    for page in data.get("pages", []):
        if page.get("parent_id") in page_id_map:
            db.execute("UPDATE pages SET parent_id = %s WHERE id = %s", (page_id_map[page["parent_id"]], page_id_map[page["id"]]))
    for tag in data.get("tags", []):
        new_tag = db.execute(
            """
            INSERT INTO tags (campaign_id, name, slug, color, created_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (campaign_id, slug) DO UPDATE SET name = excluded.name, color = excluded.color
            RETURNING id
            """,
            (
                new_campaign_id,
                tag.get("name", "Tag"),
                tag.get("slug") or slugify(tag.get("name", "Tag")),
                tag.get("color", ""),
                timestamp,
            ),
        ).fetchone()
        tag_id_map[tag["id"]] = new_tag["id"]
    for page_tag in data.get("page_tags", []):
        if page_tag.get("page_id") in page_id_map and page_tag.get("tag_id") in tag_id_map:
            db.execute(
                "INSERT INTO page_tags (page_id, tag_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                (page_id_map[page_tag["page_id"]], tag_id_map[page_tag["tag_id"]]),
            )
    for relation in data.get("page_relations", []):
        if relation.get("source_page_id") not in page_id_map:
            continue
        target_page_id = page_id_map.get(relation.get("target_page_id"))
        db.execute(
            """
            INSERT INTO page_relations (
                campaign_id, source_page_id, target_page_id, target_title,
                relation_type, description, visibility, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                new_campaign_id,
                page_id_map[relation["source_page_id"]],
                target_page_id,
                relation.get("target_title", ""),
                relation.get("relation_type", "related"),
                relation.get("description", ""),
                validated(relation.get("visibility"), PAGE_VISIBILITIES, "players"),
                timestamp,
            ),
        )
    for page in data.get("pages", []):
        if page.get("id") in page_id_map:
            sync_page_mentions(
                db,
                new_campaign_id,
                page_id_map[page["id"]],
                page.get("body", ""),
                page.get("body_private", ""),
                page.get("visibility", "players"),
            )
    for note in data.get("notes", []):
        new_note = db.execute(
            """
            INSERT INTO session_notes (campaign_id, user_id, title, body, updated_at)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                new_campaign_id,
                user["id"],
                note.get("title", "Importierte Notiz"),
                note.get("body", ""),
                timestamp,
            ),
        ).fetchone()
        note_id_map[note["id"]] = new_note["id"]
    for attachment in data.get("attachments", []):
        old_page_id = attachment.get("page_id")
        old_note_id = attachment.get("note_id")
        if old_page_id and old_page_id not in page_id_map:
            continue
        if old_note_id and old_note_id not in note_id_map:
            continue
        db.execute(
            """
            INSERT INTO attachments (campaign_id, page_id, note_id, uploaded_by, filename, mime_type, content, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                new_campaign_id,
                page_id_map.get(old_page_id),
                note_id_map.get(old_note_id),
                user["id"],
                attachment["filename"],
                attachment.get("mime_type", "application/octet-stream"),
                base64.b64decode(attachment.get("content_base64", "")),
                timestamp,
            ),
        )
    return new_campaign_id


def default_admin_settings() -> dict:
    return {
        "users": {
            "local": {
                "enabled": True,
                "allow_admin_created_users": True,
                "minimum_password_length": 8,
                "session_days": SESSION_DAYS,
                "password_reset_enabled": False,
            },
            "email": {
                "enabled": False,
                "smtp_host": "",
                "smtp_port": 587,
                "smtp_username": "",
                "from_address": "",
                "require_email_confirmation": False,
                "magic_link_login": False,
            },
            "ldap": {
                "enabled": False,
                "server_url": "",
                "bind_dn": "",
                "base_dn": "",
                "user_filter": "(mail={email})",
                "group_filter": "",
                "admin_group": "",
                "dm_group": "",
                "start_tls": True,
            },
            "two_factor": {
                "enabled": False,
                "required_for_admins": False,
                "required_for_dms": False,
                "issuer_name": "CampaignCodex",
                "remember_device_days": 30,
            },
            "oidc": {
                "enabled": oauth_enabled(),
                "issuer": OIDC_ISSUER,
                "client_id": OIDC_CLIENT_ID,
                "redirect_uri": OIDC_REDIRECT_URI,
                "admin_group": OIDC_ADMIN_GROUP,
                "dm_group": OIDC_DM_GROUP,
                "scopes": "openid email profile groups",
            },
        },
        "general": {
            "update_window": "Sonntag 03:00-04:00",
            "include_beta_releases": True,
            "update_command": os.environ.get("CAMPAIGN_CODEX_UPDATE_COMMAND", ""),
        },
    }


def load_admin_settings(db: psycopg.Connection) -> dict:
    settings = default_admin_settings()
    row = db.execute("SELECT value FROM app_settings WHERE key = 'admin'").fetchone()
    if row:
        deep_update(settings, row["value"])
    return settings


def save_admin_settings(db: psycopg.Connection, payload: dict) -> dict:
    settings = default_admin_settings()
    deep_update(settings, payload if isinstance(payload, dict) else {})
    settings["general"]["update_command"] = os.environ.get("CAMPAIGN_CODEX_UPDATE_COMMAND", "")
    db.execute(
        """
        INSERT INTO app_settings (key, value, updated_at)
        VALUES ('admin', %s::jsonb, %s)
        ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
        """,
        (json.dumps(settings), now()),
    )
    return settings


def deep_update(target: dict, source: dict) -> dict:
    for key, value in source.items():
        if isinstance(value, dict) and isinstance(target.get(key), dict):
            deep_update(target[key], value)
        elif key in target:
            target[key] = value
    return target


def admin_settings_payload(db: psycopg.Connection) -> dict:
    settings = load_admin_settings(db)
    return {
        "settings": settings,
        "runtime": {
            "version": APP_VERSION,
            "repository": APP_REPOSITORY,
            "oauth_enabled": oauth_enabled(),
            "log_file": str(LOG_FILE),
            "log": read_log_tail(),
        },
    }


def read_log_tail(max_lines: int = 240) -> str:
    if not LOG_FILE.exists():
        return "Noch keine Logdatei vorhanden."
    try:
        lines = LOG_FILE.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as error:
        return f"Logdatei konnte nicht gelesen werden: {error}"
    return "\n".join(lines[-max_lines:]) or "Logdatei ist leer."


def check_for_update(include_prereleases: bool) -> dict:
    url = f"https://api.github.com/repos/{APP_REPOSITORY}/releases"
    request = Request(url, headers={"Accept": "application/vnd.github+json", "User-Agent": "CampaignCodex"})
    try:
        with urlopen(request, timeout=12) as response:
            releases = json.loads(response.read().decode("utf-8"))
    except Exception as error:
        return {
            "ok": False,
            "current_version": APP_VERSION,
            "message": f"Release-Check fehlgeschlagen: {error}",
        }
    candidates = [
        release for release in releases
        if not release.get("draft") and (include_prereleases or not release.get("prerelease"))
    ]
    latest = candidates[0] if candidates else None
    if not latest:
        return {
            "ok": True,
            "current_version": APP_VERSION,
            "latest_version": None,
            "update_available": False,
            "message": "Keine passenden Releases gefunden.",
        }
    latest_version = str(latest.get("tag_name", "")).lstrip("v")
    return {
        "ok": True,
        "current_version": APP_VERSION,
        "latest_version": latest_version,
        "update_available": version_key(latest_version) > version_key(APP_VERSION),
        "prerelease": bool(latest.get("prerelease")),
        "url": latest.get("html_url"),
        "message": latest.get("name") or latest.get("tag_name"),
    }


def version_key(value: str) -> tuple:
    raw = clean(value).lstrip("v")
    base, _, suffix = raw.partition("-")
    numbers = tuple(int(part) for part in re.findall(r"\d+", base)[:3])
    numbers = numbers + (0,) * (3 - len(numbers))
    prerelease_rank = 0 if suffix else 1
    suffix_numbers = tuple(int(part) for part in re.findall(r"\d+", suffix))
    return (*numbers, prerelease_rank, *suffix_numbers)


def run_update_command(db: psycopg.Connection) -> dict:
    command = clean(os.environ.get("CAMPAIGN_CODEX_UPDATE_COMMAND"))
    if not command:
        return {
            "ok": False,
            "message": "Kein Update-Befehl konfiguriert. Hinterlege einen Befehl in den allgemeinen Einstellungen.",
        }
    try:
        result = subprocess.run(command, shell=True, cwd=str(ROOT), capture_output=True, text=True, timeout=600, check=False)
    except Exception as error:
        logging.exception("CampaignCodex update command failed before execution")
        return {"ok": False, "message": str(error)}
    logging.info("CampaignCodex update command exited with code %s", result.returncode)
    return {
        "ok": result.returncode == 0,
        "exit_code": result.returncode,
        "stdout": result.stdout[-6000:],
        "stderr": result.stderr[-6000:],
        "message": "Update-Befehl ausgeführt." if result.returncode == 0 else "Update-Befehl ist fehlgeschlagen.",
    }


def upsert_oauth_user(db: psycopg.Connection, userinfo: dict) -> dict:
    subject = str(userinfo["sub"])
    email = clean(userinfo.get("email")).lower()
    display_name = clean(userinfo.get("name")) or clean(userinfo.get("preferred_username")) or email
    groups = userinfo.get("groups") or []
    global_role = "player"
    if OIDC_ADMIN_GROUP in groups:
        global_role = "admin"
    elif OIDC_DM_GROUP in groups:
        global_role = "dm"
    existing = db.execute(
        "SELECT * FROM users WHERE auth_provider = 'authentik' AND auth_subject = %s",
        (subject,),
    ).fetchone()
    if not existing and email:
        existing = db.execute("SELECT * FROM users WHERE lower(email) = lower(%s)", (email,)).fetchone()
    role = "dm" if global_role in ("admin", "dm") else "player"
    if existing:
        return db.execute(
            """
            UPDATE users
            SET display_name = %s, email = %s, global_role = %s, role = %s,
                auth_provider = 'authentik', auth_subject = %s
            WHERE id = %s
            RETURNING *
            """,
            (display_name, email, global_role, role, subject, existing["id"]),
        ).fetchone()
    return db.execute(
        """
        INSERT INTO users (display_name, role, email, global_role, auth_provider, auth_subject, created_at)
        VALUES (%s, %s, %s, %s, 'authentik', %s, %s)
        RETURNING *
        """,
        (display_name, role, email, global_role, subject, now()),
    ).fetchone()


def public_user(user: dict | None) -> dict | None:
    if not user:
        return None
    return {
        "id": user["id"],
        "display_name": user["display_name"],
        "email": user.get("email"),
        "global_role": user.get("global_role", user.get("role", "player")),
        "auth_provider": user.get("auth_provider", "local"),
    }


def visible_campaigns_query(user: dict) -> str:
    if user["global_role"] == "admin":
        return "SELECT * FROM campaigns ORDER BY name"
    return """
        SELECT campaigns.*
        FROM campaigns
        JOIN memberships ON memberships.campaign_id = campaigns.id
        WHERE memberships.user_id = %s
        ORDER BY campaigns.name
    """


def visible_campaigns_params(user: dict) -> tuple:
    return () if user["global_role"] == "admin" else (user["id"],)


def oauth_enabled() -> bool:
    return bool(OIDC_ISSUER and OIDC_CLIENT_ID and OIDC_CLIENT_SECRET)


def post_form(url: str, data: dict) -> dict:
    request = Request(
        url,
        data=urlencode(data).encode("utf-8"),
        headers={"Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json"},
        method="POST",
    )
    with urlopen(request, timeout=15) as response:
        return json.loads(response.read().decode("utf-8"))


def get_json(url: str, access_token: str) -> dict:
    request = Request(url, headers={"Authorization": f"Bearer {access_token}", "Accept": "application/json"})
    with urlopen(request, timeout=15) as response:
        return json.loads(response.read().decode("utf-8"))


def hash_password(password: str) -> str:
    salt = secrets.token_hex(16)
    iterations = 260000
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), iterations)
    return f"pbkdf2_sha256${iterations}${salt}${digest.hex()}"


def verify_password(password: str, stored: str | None) -> bool:
    if not stored:
        return False
    algorithm, iterations, salt, expected = stored.split("$", 3)
    if algorithm != "pbkdf2_sha256":
        return False
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), int(iterations))
    return hmac.compare_digest(digest.hex(), expected)


def hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def make_excerpt(body: str, term: str) -> str:
    index = body.lower().find(term.lower())
    if index < 0:
        return body[:180]
    start = max(0, index - 70)
    end = min(len(body), index + 140)
    return body[start:end]


def make_page_excerpt(item: dict, term: str, include_private: bool) -> str:
    body = item.get("body", "") or ""
    if term.lower() in body.lower():
        return make_excerpt(body, term)
    private_body = item.get("body_private", "") or ""
    if include_private and term.lower() in private_body.lower():
        return make_excerpt(private_body, term)
    return make_excerpt(body or item.get("summary", ""), term)


def clean(value: object) -> str:
    return str(value or "").strip()


def validated(value: object, allowed: tuple[str, ...], fallback: str) -> str:
    candidate = clean(value)
    return candidate if candidate in allowed else fallback


def sql_tuple(values: tuple[str, ...]) -> str:
    return "(" + ", ".join(f"'{value}'" for value in values) + ")"


def main() -> None:
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        filename=str(LOG_FILE),
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )
    init_db()
    port = int(os.environ.get("PORT", "8080"))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    logging.info("CampaignCodex %s listening on http://0.0.0.0:%s", APP_VERSION, port)
    print(f"CampaignCodex {APP_VERSION} listening on http://0.0.0.0:{port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
