from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import psycopg
from psycopg.rows import dict_row


ROOT = Path(__file__).resolve().parent.parent
STATIC_DIR = ROOT / "static"
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://campaign_codex:campaign_codex@localhost:5432/campaign_codex",
)

PAGE_CATEGORIES = (
    "overview",
    "locations",
    "characters",
    "factions",
    "creatures",
    "items",
    "plots",
    "lore",
    "rules",
    "player_dossiers",
    "dm_notes",
)
PAGE_VISIBILITIES = ("dm", "players")


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def connect() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def row_to_dict(row: dict) -> dict:
    return dict(row)


def init_db() -> None:
    with connect() as db:
        db.execute(
            f"""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                display_name TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('dm', 'player')),
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS campaigns (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name TEXT NOT NULL,
                system TEXT NOT NULL DEFAULT 'D&D 5e',
                description TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS memberships (
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK(role IN ('dm', 'player')),
                PRIMARY KEY (user_id, campaign_id)
            );

            CREATE TABLE IF NOT EXISTS pages (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
                title TEXT NOT NULL,
                category TEXT NOT NULL CHECK(category IN {sql_tuple(PAGE_CATEGORIES)}),
                template_key TEXT NOT NULL DEFAULT 'generic',
                summary TEXT NOT NULL DEFAULT '',
                visibility TEXT NOT NULL CHECK(visibility IN {sql_tuple(PAGE_VISIBILITIES)}),
                body TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS session_notes (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                title TEXT NOT NULL,
                body TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
            """
        )
        has_campaigns = db.execute("SELECT COUNT(*) AS count FROM campaigns").fetchone()["count"]
        if has_campaigns:
            return

        seed_database(db)


def seed_database(db: psycopg.Connection) -> None:
    timestamp = now()
    mira_id = db.execute(
        "INSERT INTO users (display_name, role, created_at) VALUES (%s, %s, %s) RETURNING id",
        ("Mira", "dm", timestamp),
    ).fetchone()["id"]
    jonas_id = db.execute(
        "INSERT INTO users (display_name, role, created_at) VALUES (%s, %s, %s) RETURNING id",
        ("Jonas", "player", timestamp),
    ).fetchone()["id"]
    lea_id = db.execute(
        "INSERT INTO users (display_name, role, created_at) VALUES (%s, %s, %s) RETURNING id",
        ("Lea", "player", timestamp),
    ).fetchone()["id"]
    campaign_id = db.execute(
        "INSERT INTO campaigns (name, system, description, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
        (
            "Die Splitterkrone",
            "D&D 5e",
            "Eine Beispielkampagne um verlorene Erben, alte Portale und eine Krone, die niemand tragen sollte.",
            timestamp,
        ),
    ).fetchone()["id"]

    with db.cursor() as cursor:
        cursor.executemany(
            "INSERT INTO memberships (user_id, campaign_id, role) VALUES (%s, %s, %s)",
            [(mira_id, campaign_id, "dm"), (jonas_id, campaign_id, "player"), (lea_id, campaign_id, "player")],
        )
        cursor.executemany(
            """
            INSERT INTO pages (campaign_id, title, category, template_key, summary, visibility, body, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    campaign_id,
                    "Karte der Grenzlande",
                    "overview",
                    "generic",
                    "Die wichtigsten Regionen und Konflikte der Kampagne.",
                    "players",
                    "Die Grenzlande bestehen aus drei Fürstentümern, einem Nebelwald und den Ruinen von Kar Amon.",
                    timestamp,
                ),
                (
                    campaign_id,
                    "Dornwacht",
                    "locations",
                    "location",
                    "Eine befestigte Grenzstadt am Rand des Nebelwaldes.",
                    "players",
                    "Kurzbeschreibung\nEine befestigte Grenzstadt am Rand des Nebelwaldes.\n\nAtmosphäre\nNasse Steinmauern, Krähen auf den Dächern und nervöse Wachen.\n\nWichtige Orte\n- Alter Turm\n- Bürgermeisterhaus\n- Gasthaus Zur Silbernen Laterne",
                    timestamp,
                ),
                (
                    campaign_id,
                    "Arveth, Hofmagier",
                    "characters",
                    "character",
                    "Ein höflicher Hofmagier mit zu vielen Antworten.",
                    "players",
                    "Rolle in der Welt\nBerater des Fürstenhauses.\n\nAussehen und Auftreten\nRuhig, höflich, immer mit silbernem Gehstock.\n\nWas die Spieler wissen\nArveth kennt sich mit Portalen aus.",
                    timestamp,
                ),
                (
                    campaign_id,
                    "Geheimer Antagonist",
                    "dm_notes",
                    "dm_secret",
                    "Arveth arbeitet im Verborgenen gegen die Gruppe.",
                    "dm",
                    "Der Hofmagier Arveth sammelt Splitter der Krone und lenkt mehrere Fraktionen gegeneinander.",
                    timestamp,
                ),
                (
                    campaign_id,
                    "Offene Quests",
                    "plots",
                    "plot",
                    "Aktive Aufhänger und offene Kampagnenfäden.",
                    "players",
                    "- Finde die vermisste Kundschafterin.\n- Untersuche das blaue Feuer im alten Turm.",
                    timestamp,
                ),
            ],
        )

    db.execute(
        """
        INSERT INTO session_notes (campaign_id, user_id, title, body, updated_at)
        VALUES (%s, %s, %s, %s, %s)
        """,
        (
            campaign_id,
            jonas_id,
            "Session 1: Ankunft in Dornwacht",
            "Wir haben den Bürgermeister getroffen und eine Karte erhalten.",
            timestamp,
        ),
    )


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(STATIC_DIR), **kwargs)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path.startswith("/api/"):
            self.handle_api_get(parsed.path, parse_qs(parsed.query))
            return
        if parsed.path == "/":
            self.path = "/index.html"
        super().do_GET()

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        if not parsed.path.startswith("/api/"):
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        payload = self.read_json()
        self.handle_api_post(parsed.path, payload)

    def do_PUT(self) -> None:
        parsed = urlparse(self.path)
        if not parsed.path.startswith("/api/"):
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        payload = self.read_json()
        self.handle_api_put(parsed.path, payload)

    def read_json(self) -> dict:
        length = int(self.headers.get("Content-Length", "0"))
        if length == 0:
            return {}
        raw = self.rfile.read(length).decode("utf-8")
        return json.loads(raw)

    def send_json(self, data: object, status: HTTPStatus = HTTPStatus.OK) -> None:
        encoded = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def handle_api_get(self, path: str, query: dict[str, list[str]]) -> None:
        with connect() as db:
            if path == "/api/bootstrap":
                campaigns = [row_to_dict(row) for row in db.execute("SELECT * FROM campaigns ORDER BY name")]
                users = [row_to_dict(row) for row in db.execute("SELECT * FROM users ORDER BY display_name")]
                self.send_json({"campaigns": campaigns, "users": users})
                return

            if path == "/api/campaign":
                campaign_id = self.required_int(query, "campaign_id")
                user_id = self.required_int(query, "user_id")
                membership = self.membership(db, campaign_id, user_id)
                if not membership:
                    self.send_json({"error": "User is not part of this campaign."}, HTTPStatus.FORBIDDEN)
                    return

                campaign = row_to_dict(
                    db.execute("SELECT * FROM campaigns WHERE id = %s", (campaign_id,)).fetchone()
                )
                pages_query = """
                    SELECT * FROM pages
                    WHERE campaign_id = %s AND (%s = 'dm' OR visibility = 'players')
                    ORDER BY category, title
                """
                pages = [row_to_dict(row) for row in db.execute(pages_query, (campaign_id, membership["role"]))]
                notes_query = """
                    SELECT session_notes.*, users.display_name AS author
                    FROM session_notes
                    JOIN users ON users.id = session_notes.user_id
                    WHERE campaign_id = %s AND (%s = 'dm' OR user_id = %s)
                    ORDER BY updated_at DESC
                """
                notes = [
                    row_to_dict(row)
                    for row in db.execute(notes_query, (campaign_id, membership["role"], user_id))
                ]
                members = [
                    row_to_dict(row)
                    for row in db.execute(
                        """
                        SELECT users.id, users.display_name, memberships.role
                        FROM memberships
                        JOIN users ON users.id = memberships.user_id
                        WHERE campaign_id = %s
                        ORDER BY memberships.role, users.display_name
                        """,
                        (campaign_id,),
                    )
                ]
                self.send_json(
                    {
                        "campaign": campaign,
                        "membership": row_to_dict(membership),
                        "pages": pages,
                        "notes": notes,
                        "members": members,
                    }
                )
                return

        self.send_error(HTTPStatus.NOT_FOUND)

    def handle_api_post(self, path: str, payload: dict) -> None:
        timestamp = now()
        with connect() as db:
            if path == "/api/campaigns":
                name = clean(payload.get("name"))
                if not name:
                    self.send_json({"error": "Campaign name is required."}, HTTPStatus.BAD_REQUEST)
                    return
                campaign = db.execute(
                    """
                    INSERT INTO campaigns (name, system, description, created_at)
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                    """,
                    (name, clean(payload.get("system")) or "D&D 5e", clean(payload.get("description")), timestamp),
                ).fetchone()
                dm_name = clean(payload.get("dm_name")) or "Dungeon Master"
                user = db.execute(
                    "INSERT INTO users (display_name, role, created_at) VALUES (%s, 'dm', %s) RETURNING id",
                    (dm_name, timestamp),
                ).fetchone()
                db.execute(
                    "INSERT INTO memberships (user_id, campaign_id, role) VALUES (%s, %s, 'dm')",
                    (user["id"], campaign["id"]),
                )
                self.send_json({"id": campaign["id"], "dm_user_id": user["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/pages":
                campaign_id = int(payload["campaign_id"])
                user_id = int(payload["user_id"])
                membership = self.membership(db, campaign_id, user_id)
                if not membership or membership["role"] != "dm":
                    self.send_json({"error": "Only DMs can create wiki pages."}, HTTPStatus.FORBIDDEN)
                    return
                page = db.execute(
                    """
                    INSERT INTO pages (campaign_id, title, category, template_key, summary, visibility, body, updated_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        campaign_id,
                        clean(payload.get("title")) or "Neue Seite",
                        validated(payload.get("category"), PAGE_CATEGORIES, "overview"),
                        clean(payload.get("template_key")) or "generic",
                        clean(payload.get("summary")),
                        validated(payload.get("visibility"), PAGE_VISIBILITIES, "players"),
                        payload.get("body", ""),
                        timestamp,
                    ),
                ).fetchone()
                self.send_json({"id": page["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/notes":
                campaign_id = int(payload["campaign_id"])
                user_id = int(payload["user_id"])
                if not self.membership(db, campaign_id, user_id):
                    self.send_json({"error": "User is not part of this campaign."}, HTTPStatus.FORBIDDEN)
                    return
                note = db.execute(
                    """
                    INSERT INTO session_notes (campaign_id, user_id, title, body, updated_at)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        campaign_id,
                        user_id,
                        clean(payload.get("title")) or "Neue Session-Notiz",
                        payload.get("body", ""),
                        timestamp,
                    ),
                ).fetchone()
                self.send_json({"id": note["id"]}, HTTPStatus.CREATED)
                return

            if path == "/api/members":
                campaign_id = int(payload["campaign_id"])
                user_id = int(payload["user_id"])
                membership = self.membership(db, campaign_id, user_id)
                if not membership or membership["role"] != "dm":
                    self.send_json({"error": "Only DMs can add campaign members."}, HTTPStatus.FORBIDDEN)
                    return
                display_name = clean(payload.get("display_name"))
                role = payload.get("role", "player")
                if not display_name:
                    self.send_json({"error": "Display name is required."}, HTTPStatus.BAD_REQUEST)
                    return
                if role not in ("dm", "player"):
                    self.send_json({"error": "Invalid role."}, HTTPStatus.BAD_REQUEST)
                    return
                existing_user = db.execute(
                    "SELECT * FROM users WHERE lower(display_name) = lower(%s)",
                    (display_name,),
                ).fetchone()
                if existing_user:
                    new_user_id = existing_user["id"]
                else:
                    new_user_id = db.execute(
                        "INSERT INTO users (display_name, role, created_at) VALUES (%s, %s, %s) RETURNING id",
                        (display_name, role, timestamp),
                    ).fetchone()["id"]
                db.execute(
                    """
                    INSERT INTO memberships (user_id, campaign_id, role)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(user_id, campaign_id) DO UPDATE SET role = excluded.role
                    """,
                    (new_user_id, campaign_id, role),
                )
                self.send_json({"id": new_user_id}, HTTPStatus.CREATED)
                return

        self.send_error(HTTPStatus.NOT_FOUND)

    def handle_api_put(self, path: str, payload: dict) -> None:
        timestamp = now()
        with connect() as db:
            if path.startswith("/api/pages/"):
                page_id = int(path.rsplit("/", 1)[1])
                page = db.execute("SELECT * FROM pages WHERE id = %s", (page_id,)).fetchone()
                if not page:
                    self.send_error(HTTPStatus.NOT_FOUND)
                    return
                membership = self.membership(db, page["campaign_id"], int(payload["user_id"]))
                if not membership or membership["role"] != "dm":
                    self.send_json({"error": "Only DMs can edit wiki pages."}, HTTPStatus.FORBIDDEN)
                    return
                db.execute(
                    """
                    UPDATE pages
                    SET title = %s, category = %s, template_key = %s, summary = %s, visibility = %s, body = %s, updated_at = %s
                    WHERE id = %s
                    """,
                    (
                        clean(payload.get("title")) or "Unbenannte Seite",
                        validated(payload.get("category"), PAGE_CATEGORIES, page["category"]),
                        clean(payload.get("template_key")) or page["template_key"],
                        clean(payload.get("summary")),
                        validated(payload.get("visibility"), PAGE_VISIBILITIES, page["visibility"]),
                        payload.get("body", ""),
                        timestamp,
                        page_id,
                    ),
                )
                self.send_json({"ok": True})
                return

            if path.startswith("/api/notes/"):
                note_id = int(path.rsplit("/", 1)[1])
                note = db.execute("SELECT * FROM session_notes WHERE id = %s", (note_id,)).fetchone()
                if not note:
                    self.send_error(HTTPStatus.NOT_FOUND)
                    return
                user_id = int(payload["user_id"])
                membership = self.membership(db, note["campaign_id"], user_id)
                if not membership or (membership["role"] != "dm" and note["user_id"] != user_id):
                    self.send_json({"error": "You can only edit your own notes."}, HTTPStatus.FORBIDDEN)
                    return
                db.execute(
                    "UPDATE session_notes SET title = %s, body = %s, updated_at = %s WHERE id = %s",
                    (clean(payload.get("title")) or "Unbenannte Notiz", payload.get("body", ""), timestamp, note_id),
                )
                self.send_json({"ok": True})
                return

        self.send_error(HTTPStatus.NOT_FOUND)

    def membership(self, db: psycopg.Connection, campaign_id: int, user_id: int) -> dict | None:
        return db.execute(
            "SELECT * FROM memberships WHERE campaign_id = %s AND user_id = %s",
            (campaign_id, user_id),
        ).fetchone()

    def required_int(self, query: dict[str, list[str]], key: str) -> int:
        return int(query.get(key, ["0"])[0])


def clean(value: object) -> str:
    return str(value or "").strip()


def validated(value: object, allowed: tuple[str, ...], fallback: str) -> str:
    candidate = clean(value)
    return candidate if candidate in allowed else fallback


def sql_tuple(values: tuple[str, ...]) -> str:
    return "(" + ", ".join(f"'{value}'" for value in values) + ")"


def main() -> None:
    init_db()
    port = int(os.environ.get("PORT", "8080"))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"CampaignCodex listening on http://0.0.0.0:{port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
